apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: lidarflow-challenge
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: rook-cephfs
  resources:
    requests:
      storage: 8Ti
  volumeMode: Filesystem
